gpinitsystem: --ignore-warnings flag will return 0 on warnings
Previously gpinitsystem returned 1 in case of warnings (2 in case of
errors). We have changed gpinitsystem to return 0 for warnings so that
other tools using gpinitsystem (such as gpupgrade) will not fail when
gpinitsystem generates warnings. This behavior is only available when
specifying the --ignore-warnings flag. Existing exit code behavior
remains the same when the flag is not specified.

Also, gpinitsystem was exiting with non-zero return code if certain
errors or warnings had happened on any previous run of gpinitsystem that
day. This has also been fixed in this commit, in the case where
--ignore-warnings is specified.

Co-authored-by: Mark Sliva <msliva@pivotal.io>

diff --git a/gpMgmt/bin/gpinitsystem b/gpMgmt/bin/gpinitsystem
--- a/gpMgmt/bin/gpinitsystem
+++ b/gpMgmt/bin/gpinitsystem
@@ -20,6 +20,26 @@
 #******************************************************************************
 # Prep Code
 
+IGNORE_WARNINGS=0
+
+POSITIONAL=()
+while [[ $# -gt 0 ]]
+do
+key="$1"
+
+case $key in
+    --ignore-warnings)
+    IGNORE_WARNINGS=1
+    shift # past argument
+    ;;
+    *)    # next argument
+    POSITIONAL+=("$1") # save it in an array for later
+    shift # past argument
+    ;;
+esac
+done
+set -- "${POSITIONAL[@]}" # restore positional parameters
+
 WORKDIR=`dirname $0`
 
 # Source required functions file, this required for script to run
@@ -31,7 +51,11 @@ if [ -f $FUNCTIONS ]; then
     . $WORKDIR/lib/gp_bash_version.sh
 else
     echo "[FATAL]:-Cannot source $FUNCTIONS file, script Exits!"
-    exit 2
+	if [ $IGNORE_WARNINGS -eq 1 ]; then
+		exit 1
+	else
+		exit 2
+	fi
 fi
 
 #******************************************************************************
@@ -163,9 +187,14 @@ USAGE () {
 		$ECHO
 		$ECHO "      Return codes:"
 		$ECHO "      0 - No problems encountered with requested operation"
-		$ECHO "      1 - Warning generated, but instance operational"
-		$ECHO "      2 - Fatal error, instance not created/started, or in an inconsistent state,"
-		$ECHO "          see log file for failure reason."
+		if [ $IGNORE_WARNINGS -eq 1 ]; then
+			$ECHO "      1 - Fatal error, instance not created/started, or in an inconsistent state,"
+			$ECHO "          see log file for failure reason."
+		else
+			$ECHO "      1 - Warning generated, but instance operational"
+			$ECHO "      2 - Fatal error, instance not created/started, or in an inconsistent state,"
+			$ECHO "          see log file for failure reason."
+		fi
 		$ECHO
 		exit $EXIT_STATUS
 	fi
@@ -329,7 +358,9 @@ CHK_PARAMS () {
 		# Now process contents for the configuration file
 		if [ ! "$ARRAY_NAME" ]; then
 			LOG_MSG "[WARN]:-ARRAY_NAME variable not set, will provide default value" 1
-			EXIT_STATUS=1
+			if [ $IGNORE_WARNINGS -ne 1 ]; then
+				EXIT_STATUS=1
+			fi
 			ARRAY_NAME="Greenplum Instance"
 		fi
 		export ARRAY_NAME
@@ -402,7 +433,9 @@ CHK_PARAMS () {
 		# ENCODING
 		if [ ! $ENCODING ]; then
 			LOG_MSG "[WARN]:-ENCODING variable not set, will set to default UTF-8" 1
-			EXIT_STATUS=1
+			if [ $IGNORE_WARNINGS -ne 1 ]; then
+				EXIT_STATUS=1
+			fi
 			ENCODING="UTF-8"
 		fi
 		if [ x"SQL_ASCII" = x"$ENCODING" ]; then
@@ -467,7 +500,9 @@ CHK_PARAMS () {
 		MASTER_OPEN=`ulimit -n`
 		if [ $MASTER_OPEN -lt $OS_OPENFILES ];then
 			LOG_MSG "[WARN]:-Master open file limit is $MASTER_OPEN should be >= $OS_OPENFILES" 1
-			EXIT_STATUS=1
+			if [ $IGNORE_WARNINGS -ne 1 ]; then
+				EXIT_STATUS=1
+			fi
 			ULIMIT_WARN=1
 		fi
 		# Get IP address of the master host
@@ -487,7 +522,9 @@ CHK_PARAMS () {
 			STANDBY_MASTER_OPEN=`$TRUSTED_SHELL $STANDBY_HOSTNAME "ulimit -n"`
 			if [ $STANDBY_MASTER_OPEN -lt $OS_OPENFILES ];then
 				LOG_MSG "[WARN]:-Standby Master open file limit is $STANDBY_MASTER_OPEN should be >= $OS_OPENFILES" 1
-				EXIT_STATUS=1
+				if [ $IGNORE_WARNINGS -ne 1 ]; then
+					EXIT_STATUS=1
+				fi
 				ULIMIT_WARN=1
 			fi
 		fi
@@ -673,7 +710,9 @@ END_PYTHON_CODE
 	if [ $MIRRORING -eq 0 ] && [ $MIRROR_TYPE -eq 1 ];then
 		LOG_MSG "[WARN]:-Option --mirror-mode supplied, but no mirrors have been defined, ignoring --mirror-mode option" 1
 		MIRROR_TYPE=0
-		EXIT_STATUS=1
+		if [ $IGNORE_WARNINGS -ne 1 ]; then
+			EXIT_STATUS=1
+		fi
 	fi
 	LOG_MSG "[INFO]:-Commencing multi-home checks, Completed" 1
 	LOG_MSG "[INFO]:-End Function $FUNCNAME"
@@ -725,7 +764,9 @@ CHK_OPEN_FILES () {
 	OPEN_VALUE=`$TRUSTED_SHELL $1 "ulimit -n"`
 	if [ $OPEN_VALUE -lt $OS_OPENFILES ];then
 		LOG_MSG "[WARN]:-Host $1 open files limit is $OPEN_VALUE should be >= $OS_OPENFILES" 1
-		EXIT_STATUS=1
+		if [ $IGNORE_WARNINGS -ne 1 ]; then
+			EXIT_STATUS=1
+		fi
 		ULIMIT_WARN=1
 	fi
 	LOG_MSG "[INFO]:-End Function $FUNCNAME"
@@ -796,7 +837,9 @@ CHK_QES () {
             LOG_MSG "[WARN]:-This will cause segment->master communication failures" 1
             LOG_MSG "[WARN]:-Remove $GP_HOSTADDRESS from local host line in /etc/hosts" 1
             LOG_MSG "[WARN]:-----------------------------------------------------------" 1
-            EXIT_STATUS=1
+			if [ $IGNORE_WARNINGS -ne 1 ]; then
+				EXIT_STATUS=1
+			fi
         fi
         # Check that we can write to the QE directory
         W_DIR=`$DIRNAME $GP_DIR`
@@ -1486,7 +1529,9 @@ STOP_QD_PRODUCTION () {
 	case $RETVAL in
 	    0 ) LOG_MSG "[INFO]:-Successfully shutdown the new Greenplum instance" ;;
 	    1 ) LOG_MSG "[WARN]:-Non fatal error from Greenplum instance shutdown, check log files, will continue"
-		EXIT_STATUS=1 ;;
+			if [ $IGNORE_WARNINGS -ne 1 ]; then
+				EXIT_STATUS=1
+			fi ;;
 	    * ) ERROR_EXIT "[FATAL]:-Failed to stop new Greenplum instance, check log file" 2
 	esac
     else
@@ -1500,7 +1545,9 @@ CREATE_STANDBY_QD () {
 	if [ ! -f $INIT_STANDBY_PROG ]; then
 		LOG_MSG "[WARN]:-Unable to locate $INIT_STANDBY_PROG, hence unable to initialize standby master $STANDBY_HOSTNAME"
 		STANDBY_RET_CODE=${STANDBY_FATAL_RET_CODE}
-		EXIT_STATUS=1
+		if [ $IGNORE_WARNINGS -ne 1 ]; then
+			EXIT_STATUS=1
+		fi
 	else
 		LOG_MSG "[INFO]:-Starting initialization of standby master $STANDBY_HOSTNAME" 1
 		INIT_STANDBY_ARGS=""
@@ -1634,7 +1681,9 @@ SCAN_LOG () {
 		LOG_MSG "[INFO]:-that was called today!" 1
 		fi
 		LOG_MSG "[WARN]:-*******************************************************" 1
-		EXIT_STATUS=1
+		if [ $IGNORE_WARNINGS -ne 1 ]; then
+			EXIT_STATUS=1
+		fi
 	else
 		LOG_MSG "[INFO]:-Log file scan check passed" 1
 	fi
@@ -1914,12 +1963,13 @@ while getopts ":vaqe:c:l:-:p:m:h:n:s:P:S:b:DB:I:O:" opt
 						"standby-datadir" ) STANDBY_DATADIR=$VAL ;;
 						"help"            ) USAGE "print_doc" ;;
 						"version"         ) print_version ;;
+						"ignore-warnings" ) IGNORE_WARNINGS=1 ;;
 						* ) LOG_MSG "[ERROR]:-Unknown option --$NAME" 1; USAGE ;;
 					esac
 
 					# Check if we are missing the long option value.  Currently all
 					# long options require a value so we can just do the check once.
-					if [ x"$NAME" == x"$VAL" ]; then
+					if [ x"$NAME" == x"$VAL" ] && [ x"$NAME" != x"ignore-warnings" ]; then
 						LOG_MSG "[FATAL]:-Missing value for option --$NAME" 1;
 						USAGE;
 					fi
